### ISSUE TITLE
Hente veientilarbeid fra gcp

### ISSUE THREAD

**Issue by theagilepadawan** [navikt/dittnav#439]
Vi holder på å flytte over **veientilarbeid** til gcp. For at vta skal kunne hentes fra gcp til sbs, så kan vi ikke lenger bruke service discovery. For at dette skal fungere er man nødt til å bruke ingresser. 

Vi har sett på dette, og en mulig løsning vil være å legge til ingresser for hvert miljø og hente ut denne i decoratoren: 
F.eks. som vist under, ved hjelp av VEIENTILARBEID_URL-miljøvariabel som settes i hvert miljø.
```
proxy:
  - contextPath: /person/dittnav/veientilarbeid
    baseUrl: {{ VEIENTILARBEID_URL }}
    validateOidcToken: false
    requestRewrite: REMOVE_CONTEXT_PATH
    minSecurityLevel: 3
```
Med dette kan man forenkle oppsettet ved å fjerne service redirect tjenesten som er satt opp i dag.

Vi ønsker å teste dette først i prod, slik at det settes opp med en ingress for dev, mens service discovery-tjenesten fremdeles blir værende for prod.
